apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b63v4bjs8-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b63v4bjs8-nodejs 
  name: b63v4bjs8-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: b63v4bjs8-nodejs 
